name: Sync Fork

on:
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - id: sync
        uses: pauln/fork-sync@v1.7.0
        with:
          owner: minhealthnz
          base: main
          head: main
          retries: 1
          ignore_fail: true

    outputs:
      changes_applied: ${{ steps.sync.outputs.changes_applied }}

  auto-update:
    runs-on: ubuntu-latest
    needs: sync

    steps:
      - uses: actions/checkout@v3
      - uses: pauln/nz-covid-data-updater@v0.1.0
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update daily case data breakdown
