name: Sync Fork

on:
  schedule:
    - cron: '5/15 0,1 * * *'
    - cron: '0 2-8 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: pauln/fork-sync@v1.7.0
        with:
          owner: minhealthnz
          base: main
          head: main
          retries: 1

  auto-update:
    runs-on: ubuntu-latest
    needs: sync
    if: needs.sync.outputs.changes_applied

    steps:
      - uses: actions/checkout@v3
      - uses: pauln/nz-covid-data-updater@v0.0.2
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update daily case data breakdown
