name: Sync Fork

on:
  schedule:
    - cron: '5/15 0,1 * * *'
    - cron: '0 2-8 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: minhealthnz
          base: main
          head: main
