name: Update Data

on:
  workflow_dispatch: # on button click

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pauln/nz-covid-data-updater@v0.1.0
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update daily case data breakdown
